SELECT DISTINCT(car.CAR_ID) AS CARID
FROM CAR_RENTAL_COMPANY_CAR car
INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY history ON car.CAR_ID = history.CAR_ID
AND MONTH(START_DATE) = 10 AND CAR_TYPE = '세단'
ORDER BY CARID DESC