SELECT 
    SUM(GR.SCORE) AS SCORE, GR.EMP_NO, EMP.EMP_NAME, EMP.POSITION, EMP.EMAIL
FROM 
    HR_EMPLOYEES EMP
JOIN 
    HR_GRADE GR ON EMP.EMP_NO = GR.EMP_NO
GROUP BY 
    GR.EMP_NO
ORDER BY 
    SCORE DESC
LIMIT 
    1;
