SELECT 
BO.BOOK_ID, 
AU.AUTHOR_NAME, 
DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM AUTHOR AU 
JOIN BOOK BO ON AU.AUTHOR_ID = BO.AUTHOR_ID
WHERE BO.CATEGORY LIKE '경제'
ORDER BY BO.PUBLISHED_DATE ASC;