SELECT
    b.CATEGORY, SUM(bs.SALES)
FROM 
    BOOK b, BOOK_SALES bs
WHERE 
    b.BOOK_ID = bs.BOOK_ID AND Month(SALES_DATE) = 01 AND Year(SALES_DATE) = 2022
GROUP BY 
    b.CATEGORY
ORDER BY 
    b.CATEGORY;